In [1]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import random

In [2]:
data = pd.read_csv("iris.csv")
print(data)
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [4]:
knn = KNeighborsClassifier(n_neighbors=5, metric='minkowski')
knn.fit(X_train, y_train)

pred = knn.predict(X_test)

In [5]:
cm = confusion_matrix(y_test, pred)
print('Confusion Matrix:\n', cm)

Confusion Matrix:
 [[11  0  0]
 [ 0 12  1]
 [ 0  0  6]]


In [6]:
print('Accuracy Metrics')
print(classification_report(y_test, pred))

Accuracy Metrics
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        11
  versicolor       1.00      0.92      0.96        13
   virginica       0.86      1.00      0.92         6

    accuracy                           0.97        30
   macro avg       0.95      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [7]:
print("Correct Predictions:", accuracy_score(y_test, pred))
print("Wrong Predictions:", (1 - accuracy_score(y_test, pred)))

Correct Predictions: 0.9666666666666667
Wrong Predictions: 0.033333333333333326


In [8]:
sl = round(random.uniform(4.3, 7.9),2)
sw = round(random.uniform(2.0, 4.4),2)
pl = round(random.uniform(1.0, 6.9),2)
pw = round(random.uniform(0.1, 2.5),2)
sample = [[sl, sw, pl, pw]]
print(sample)
print("Sample Prediction:", knn.predict(sample))

[[6.25, 3.46, 6.44, 1.52]]
Sample Prediction: ['virginica']
